FFM-5306 - Update Java SDK to Match Variations for Prereqs With Ident…
harness/ff-java-server-sdk pull request #119
Opened 2022-11-15 12:38 UTC by andybharness

FFM-5306 - Update Java SDK to Match Variations for Prereqs With Identifier Instead of Values

**What**
When a feature depends on another prereq feature being true, the evaluation fails if the value and identifier are different values in the prereq.

**Why**
The checkPreRequisite() method incorrectly uses the value of the prereq instead of the identifier.

**Testing**
Manual + unit testing. Created flags with prereqs on app.harness.io, exported JSON into a local test case and added a new test called shouldCorrectlyEvaluatePrereqsIfIdAndValueDiffer()

2022-11-15 17:07 UTC, laura135 reviewed
LGTM but could you add a test for a multivariate flag alongside the boolean one?

2022-11-15 18:34 UTC, laura135 approved these changes

2022-11-16 10:18 UTC, davejohnston approved these changes
I think this change looks good.
It's worth calling out there is a 'tests' submodule here https://github.com/harness/ff-java-server-sdk/tree/main/src/test

Inside that submodule there is a pre-req evaluation test, but the issue is that the pre-req flag identifier is the same as the value.  It might be worth updating the test case https://github.com/drone/ff-test-cases/blob/561740a9c62f84cf87a58f4a69e26e5f38ed64b6/tests/prereq.json.  Then updating the sub-module.    CC @bmjen the same would apply to the Ruby change - possibly we could cordiante updating the sdk tests submodule so it benifits both the ruby and java PRs?

2022-11-16 15:05 UTC, bmjen requested changes
Looks good, but would like the version updated to `1.1.7` and for this to go into `main` so we can release from there.

2022-11-16 17:17 UTC, merged